GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Full Stack Open",
  "author": "University of Helsinki",
  "url": "https://fullstackopen.com",
  "likes": 5
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "cedry",
  "name": "Cedro",
  "password": "6a184037a5af5e726bbdb368",
  "likes": 5
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

# {
#   "username": "cedry",
#   "name": "Cedro",
#   "password": "12345678",
#   "likes": 5
# },
{
  "username": "cedry",
  "name": "Cedro",
  "password": "12345678",
  "likes": 5
}

###

DELETE  http://localhost:3003/api/blogs/6a18075b53f049be7bf4eaf6
Content-Type: application/json

###

PUT  http://localhost:3003/api/blogs/6a11a31ec03d63840c5d1b25
Content-Type: application/json

{
  "title": "Full Stack",
  "author": "University of Helsinki",
  "url": "https://fullstackopen.com",
  "likes": 100,
  "id": "6a11a31ec03d63840c5d1b25"
}